; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Whiffle"
#define MyAppVersion "15.0"
#define MyAppPublisher "Whiffle Co"
#define MyAppURL "https://whiffle.co/"
#define MyAppExeName "Whiffle.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{55c38bf6-23ff-4ff2-bcc2-f44cb91070e4}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
; Specify the architecture (e.g., x64) to install in 64-bit mode
ArchitecturesInstallIn64BitMode=x64
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Use {programfiles} constant - it respects ArchitecturesInstallIn64BitMode
DefaultDirName={commonpf64}\{#MyAppName} 
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=Output
OutputBaseFilename=WhiffleSetup
SetupIconFile=assets/pinball_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main executable
Source: "Whiffle\Whiffle.exe"; DestDir: "{app}"; Flags: ignoreversion
; Icon file for shortcuts
Source: "Whiffle\assets\pinball_icon.ico"; DestDir: "{app}\assets"; Flags: ignoreversion
; Other files in the root directory
Source: "Whiffle\.env"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\data\achievements\achievements.json"; DestDir: "{app}\data\achievements"; Flags: ignoreversion
Source: "Whiffle\data\achievements\achievements_status.json"; DestDir: "{app}\data\achievements"; Flags: ignoreversion
Source: "Whiffle\assets\game_over.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "Whiffle\data\scores\high_scores.json"; DestDir: "{app}\data\scores"; Flags: ignoreversion
Source: "Whiffle\configs\hsv_ranges.json"; DestDir: "{app}\configs"; Flags: ignoreversion
Source: "Whiffle\configs\settings.json"; DestDir: "{app}\configs"; Flags: ignoreversion
Source: "Whiffle\README.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\data\game\scoring_zones.json"; DestDir: "{app}\data\game"; Flags: ignoreversion
Source: "Whiffle\assets\splash.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "Whiffle\assets\splash2.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "Whiffle\assets\top_bar.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "Whiffle\assets\menu_bar.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "Whiffle\assets\column.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "Whiffle\assets\last_frame.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "Whiffle\assets\pinball_icon.png"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "Whiffle\data\scores\whiffle_leaderboard.json"; DestDir: "{app}\data\scores"; Flags: ignoreversion
Source: "Whiffle\data\whiffle_new_best.pt"; DestDir: "{app}\data"; Flags: ignoreversion
Source: "Whiffle\openh264-1.8.0-win64.dll"; DestDir: "{app}"; Flags: ignoreversion
; Sounds folder (including all files inside)
Source: "Whiffle\data\sounds\*"; DestDir: "{app}\data\sounds"; Flags: ignoreversion recursesubdirs createallsubdirs
; Google API configuration files
Source: "Whiffle\configs\client_secrets.json"; DestDir: "{app}\configs"; Flags: ignoreversion
Source: "Whiffle\configs\google_credentials.json"; DestDir: "{app}\configs"; Flags: ignoreversion
Source: "Whiffle\configs\google_credentials2.json"; DestDir: "{app}\configs"; Flags: ignoreversion
Source: "Whiffle\configs\token.pickle"; DestDir: "{app}\configs"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\pinball_icon.ico"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\pinball_icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
; Create directories with write permissions
Name: "{app}\configs"; Permissions: everyone-full
Name: "{app}\high_score_proof"; Permissions: everyone-full