; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Whiffle"
#define MyAppVersion "13.2"
#define MyAppPublisher "Whiffle Co"
#define MyAppURL "https://whiffle.co/"
#define MyAppExeName "Whiffle.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{55c38bf6-23ff-4ff2-bcc2-f44cb91070e4}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=Output
OutputBaseFilename=WhiffleSetup
SetupIconFile=pinball_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main executable
Source: "Whiffle\Whiffle.exe"; DestDir: "{app}"; Flags: ignoreversion
; Icon file for shortcuts
Source: "pinball_icon.ico"; DestDir: "{app}"; Flags: ignoreversion
; Other files in the root directory
Source: "Whiffle\.env"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\achievements.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\achievements_status.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\game_over.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\high_scores.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\hsv_ranges.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\README.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\scoring_zones.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\splash.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\splash2.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\last_frame.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\whiffle_leaderboard.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "Whiffle\whiffle_new_best.pt"; DestDir: "{app}"; Flags: ignoreversion
; Sounds folder (including all files inside)
Source: "Whiffle\sounds\*"; DestDir: "{app}\sounds"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\pinball_icon.ico"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\pinball_icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent