; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Whiffle"
#define MyAppVersion "15.7"
#define MyAppPublisher "Whiffle Co"
#define MyAppURL "https://whiffle.co/"
#define MyAppExeName "Whiffle.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{55c38bf6-23ff-4ff2-bcc2-f44cb91070e4}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
; Specify the architecture (e.g., x64) to install in 64-bit mode
ArchitecturesInstallIn64BitMode=x64
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Use {programfiles} constant - it respects ArchitecturesInstallIn64BitMode
DefaultDirName={commonpf64}\{#MyAppName} 
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=Output
OutputBaseFilename=WhiffleSetup
SetupIconFile=assets/pinball_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Copy entire PyInstaller output: Whiffle.exe + _internal (Python runtime, DLLs, torch, ultralytics, bundled data).
; The app will not run without _internal. Use the "Whiffle" folder from dist\Whiffle after "pyinstaller game.spec".
Source: "Whiffle\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Icon is under _internal when using PyInstaller default onedir layout
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\_internal\assets\pinball_icon.ico"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\_internal\assets\pinball_icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  AppDir: String;
begin
  if CurStep = ssPostInstall then
  begin
    AppDir := ExpandConstant('{app}');
    { Grant Users full control on the entire Whiffle install dir so the app can save configs, scores, zones, etc. }
    if Exec(ExpandConstant('{sys}\icacls.exe'), '"' + AppDir + '" /grant Users:(OI)(CI)F /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    begin
      if ResultCode <> 0 then
        Log('icacls returned ' + IntToStr(ResultCode) + ' for ' + AppDir);
    end
    else
      Log('Failed to run icacls for ' + AppDir);
  end;
end;

[Dirs]
; Ensure top-level app dir exists (icacls in [Code] above makes it and everything below it read/write for Users)
Name: "{app}"; Permissions: everyone-full