# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['game.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('background_music.mp3', '.'),
        ('ding.wav', '.'),
        ('logo.png', '.'),
        ('splash.png', '.'),
        ('hsv_ranges.json', '.'),
        ('scoring_zones.json', '.'),
        ('achievements.json', '.'),
        ('whiffle_leaderboard.json', '.'),
        ('whiffle_new_best.pt', '.')
    ],
    hiddenimports=[
        'numpy.core',
        'numpy.core.multiarray',
        'numpy.core.overrides',
        'numpy.core.numeric',
        'numpy.core.umath',
        'numpy.core._methods'
    ],
    hookspath=['.'],  # Include the current directory for custom hooks
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        '_pycache_',
        'dataset',
        'runs',
        'cv2.dnn',
        'cv2.gapi',
        'cv2.videoio',
        'cv2.ml',
        'cv2.cuda',
        'cv2.bgsegm',
        'cv2.aruco',
        'cv2.face',
        'cv2.optflow',
        'cv2.plot',
        'cv2.quality',
        'cv2.tracking',
        'cv2.xfeatures2d',
        'cv2.ximgproc',
        'cv2.xphoto',
        'ultralytics.models',
        'ultralytics.data',
        'ultralytics.nn',
        'ultralytics.utils',
        'ultralytics.engine',
        'tkinter',
        'PIL',
        'matplotlib',
        'scipy',
        'torchvision',
        'pandas',
        'numpy.distutils',
        'numpy.f2py',
        'numpy.testing',
        'numpy.linalg',
        'numpy.fft',
        'numpy.polynomial',
        'numpy.random'
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='WhiffleTracker',
    debug=True,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='pinball_icon.ico',
    onefile=False  # Changed to False to build as a directory bundle
)